### ISSUE TITLE
Plugin appears to be non-functional

### ISSUE THREAD

**Issue by law** [obazoud/sensu-plugins-kafka#1]
Tried the listed installation instructions, with no success.  "sensu-install" does not track the kafka plugin.  Attempted a manual clone of the repo, but there seems to be some additional fiddling needed as the ruby scripts as-is are searching for libraries/gems not in the default library paths.

**Comment by johntdyer** [comment]
+1

**Comment by obazoud** [comment]
It is not yet deployed to rubygems and it's required a kafka install to run shell
