### ISSUE TITLE
Not published to Rubygems?

### ISSUE THREAD

**Issue by CVTJNII** [obazoud/sensu-plugins-kafka#2]
I can't seem to locate this gem on Rubygems: https://rubygems.org/search?query=sensu-plugins-kafka

This makes installing more difficult and breaks the standard install instructions on http://sensu-plugins.io/docs/installation_instructions.html.  Can this gem please be published?

**Comment by kaushiksriram100** [comment]
+1

**Comment by obazoud** [comment]
Done.

https://rubygems.org/gems/sensu-plugins-kafka
