### ISSUE TITLE
wrong homepage URL set to rubygems

### ISSUE THREAD

**Issue by alexandrustaetu** [obazoud/sensu-plugins-kafka#21]
Hello,

The [homepage url](https://github.com/sensu-plugins/sensu-plugins-kafka) set for this plugin in the [rubygems repo page](https://rubygems.org/gems/sensu-plugins-kafka/versions/0.11.0) looks to point to the [sensu-plugins github group](https://github.com/sensu-plugins). 

Is there any change to have this repo/ownership be moved to the sensu-plugins group ? This might bring more contributors to this project.

Thanks,
Alex.

**Comment by obazoud** [comment]
See https://github.com/obazoud/sensu-plugins-kafka/blob/master/sensu-plugins-kafka.gemspec#L20

**Comment by alexandrustaetu** [comment]
I can do a pull request to change the url to https://github.com/obazoud/sensu-plugins-kafka .

As an alternative idea, any chance we'll see this project transferred to https://github.com/sensu-plugins ?

**Comment by yuri-zubov** [comment]
@obazoud Why don't you want to transfer plugin to the community?
https://github.com/sensu-plugins/community/issues/65

**Comment by majormoses** [comment]
@obazoud as a maintainer for https://github.com/sensu-plugins I would love to transfer these over to the community and would invite you to keep maintaining the awesome work you have done. Let me know if I can help in any way. If you are interested please respond here or to the [open issue here](https://github.com/sensu-plugins/community/issues/65). Just to give you a heads up on the basic process you can read about it [here](https://github.com/sensu-plugins/community/blob/master/TRANSFERRING_REPOS.md)

**Comment by majormoses** [comment]
I have opened a PR but based on the lack of traction here I dont think it will be merged so I will work on this weekend renaming the community one to `sensu-plugins-kafka2` to avoid the namespace conflict and attempt to reduce maintenance overhead for people sending issues to the wrong repo.

**Comment by obazoud** [comment]
PR merged

**Comment by majormoses** [comment]
Awesome, can you please do a release on rubygems.org so that it will be updated there?
